### ISSUE TITLE
Использование CI для «релизов»

### ISSUE THREAD

**Issue by ZyX-I** [latex-g7-32/latex-g7-32#43]
Предлагаю написать .travis.yml, чтобы travis автоматически собирал PDF‐ки, лучше даже четырьмя способами (cmake, make) × (pdflatex, xelatex). Можно также с помощью travis сразу выкладывать куда‐то. Я собираюсь для своего диплома сделать нечто подобное, т.к. научный руководитель просил отправлять ему PDF’ки, но это будет в одном виде (cmake + xelatex), и на bitbucket pipelines — для своих проектов я обычно выбираю bitbucket + mercurial.

Замечу, что в https://github.com/latex-g7-32/latex-g7-32/releases последний «релиз» был 28 апреля 2014 года. А README всё ещё ссылается туда, утверждая, что там результаты. Самый простой способ, по моему мнению —

1. Создать сайт latex-g7-32.github.io, создав репозиторий, принадлежащий компании «latex-g7-32» и названный «latex-g7-32.github.io».
2. Создать ключ для travis, сохранив его публичную часть в `Settings`/`Deploy keys`.
3. Создать `.travis.yml` следующего содержания:

    ```YAML
    sudo: false
    dist: precise
    os: linux
    language: c
    addons:
        apt:
            packages:
                - texlive-full
                - inkscape
                - make
                - cmake
                - dia
                - graphviz
                - python-pygments
    script: ./ci/build.sh
    after_success: ./ci/deploy.sh
    matrix:
        include: [{}]
    ```
4. Создать исполняемые скрипты:

    ci/build.sh:

    ```shell
    #!/bin/sh

    set -e
    set -x

    ARGS_make_pdflatex="LATEX=pdflatex"
    ARGS_make_xelatex=""
    ARGS_cmake_pdflatex="-DPREFER_XELATEX=false"
    ARGS_cmake_xelatex=""

    build() {
        local buildsystem=$1 ; shift
        local latex=$2 ; shift

        git clone --depth=1 -b travis-current-commit . ../temp
        pushd ../temp

        if test $buildsystem = cmake ; then
            mkdir build
            pushd build
            eval 'cmake .. $ARGS_cmake_'$latex
            make
            cp rpz.pdf ..
            popd
        else
            eval 'make $ARGS_make_'$latex
        fi

        cp rpz.pdf ../result/rpz-${buildsystem}-${latex}.pdf

        popd
        rm -rf ../temp
    }

    mkdir ../result
    git checkout -b travis-current-commit

    for buildsystem in make cmake ; do
        for latex in pdflatex xelatex ; do
            build ${buildsystem} ${latex}
        done
    done
    ```

    ci/deploy.sh:

    ```shell
    #!/bin/sh

    set -e
    set -x

    chmod 0600 ci/keys/id_rsa
    mv ci/keys/id_rsa ~/.ssh
    git clone ssh://git@github.com/latex-g7-32/latex-g7-32.github.io ../site

    git config --global user.name 'Travis CI bot'
    git config --global user.email 'bot@example.com'
    git config --global push.default simple

    SHA="$(git rev-parse HEAD)"

    pushd ../site
    for file in ../results/*.pdf ; do
        base="$(basename "$file")"
        tgt_fname="${SHA}-$base"
        ln "$file" "$tgt_fname"
        ln -f "${tgt_fname}" "${base}"
        git add "$base" "$tgt_fname"
    done
    echo "${SHA}: $(date --utc +"%Y-%m-%d %H:%M")" >> filelist.txt
    git add filelist.txt
    popd
    ```
5. Включить travis, установить `travis` gem (нужен ruby и rubygems), убедиться, что он понимает, с каким репозиторием работать.
6. Положить в ci/keys/ приватную часть ключа. Зашифровать её с помощью `travis encrypt-file --add before_install --decrypt-to ci/keys/id_rsa ci/keys/id_rsa`. Сделать commit с зашифрованным файлом.
7. Если я нигде не ошибся, то после push оно заработает. Можно будет поправить README, указав, что примеры находятся в `latex-g7-32.github.io/rpz-{cmake,make}-{pdflatex,xelatex}.pdf`.
